
llama-7b:
  block_size: 16
  num_attention_layers: 32
  num_heads: 32
  head_size: 128
  dtype_size: 2  # float16
  max_seq_len: 2048   # max_num_batched_tokens = max(max_model_len, 2048)
  1:
    gpu_block: 3806
    cpu_block: 512
    weight_size: 12.5518
  2:
    gpu_block: 9145
    cpu_block: 1024
    weight_size: 6.3096
  4:
    gpu_block: 18660
    cpu_block: 2048
    weight_size: 3.1856
  8:
    gpu_block: 38936
    cpu_block: 4096
    weight_size: 1.5869
llama-13b:
  block_size: 16
  num_attention_layers: 40
  num_heads: 40
  head_size: 128
  dtype_size: 2  # float16  
  max_seq_len: 2048
  1:
    gpu_block: 1475
    cpu_block: 327
    weight_size: 24.2835  # tp:size in GB
  2:
    gpu_block: 4860
    cpu_block: 655
    weight_size: 12.2596
  4:
    gpu_block: 10946
    cpu_block: 1310
    weight_size: 6.1109
  8:
    gpu_block: 23900
    cpu_block: 2621
    weight_size: 3.0433